server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

  resources:
    static-locations: classpath:/META-INF/resources

  redis:
    host: localhost
    port: 6379
    password:
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
      max-wait: 2
    timeout: 2000


#  rabbitmq:
#    addresses: 192.168.15.203:5672
#    username: root
#    password: password
##    addresses: 172.16.137.140:5672
##    username: admin
##    password: admin
#
##开启发送确认
#    publisher-confirms: true
##开启发送失败退回
#    publisher-returns: true
#    virtual-host: /
#    listener:
#      simple:
#        acknowledge-mode: manual

##########访问页面时出现  需要身份验证  添加一下配置可以解决
#security:
#  user:
#    name: root
#    password: root