spring:
  datasource:
    url: jdbc:mysql://192.168.1.83:3306/trade5
    username: trade
    password: trade83
    driver-class-name: com.mysql.jdbc.Driver

  rabbitmq:
    addresses: 172.16.137.140:5672
    username: admin
    password: admin
    publisher-confirms: true
    virtual-host: /
