spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

  rabbitmq:
    addresses: 172.16.137.140:5672
    username: admin
    password: admin
    publisher-confirms: true
    virtual-host: /
